services:
  web:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:fpm-alpine
    volumes:
      - ./app:/var/www/html
